//This file is automatically generated. DO NOT EDIT!

#include <RobotRaconteur.h>
#include <boost/signals2.hpp>
#include "edu__rpi__cats__sensors__camera_interface.h"
#pragma once

namespace edu
{
namespace rpi
{
namespace cats
{
namespace sensors
{
namespace kinect2
{

class KinectBody;
class KinectMultiSource;
class Kinect;

class KinectBody : public RobotRaconteur::RRStructure {
public:
uint64_t tracking_id;
uint8_t tracked;
RR_SHARED_PTR<RobotRaconteur::RRArray<double > > lean;
RR_SHARED_PTR<RobotRaconteur::RRArray<double > > joint_positions;
RR_SHARED_PTR<RobotRaconteur::RRArray<double > > joint_orientations;
RR_SHARED_PTR<RobotRaconteur::RRArray<uint8_t > > joint_tracking_state;
RR_SHARED_PTR<RobotRaconteur::RRArray<uint8_t > > hand_state;
RR_SHARED_PTR<RobotRaconteur::RRArray<uint8_t > > hand_confidence;

virtual std::string RRType() {return "edu.rpi.cats.sensors.kinect2.KinectBody";  }
};

class KinectMultiSource : public RobotRaconteur::RRStructure {
public:
uint8_t Color;
uint8_t Depth;
uint8_t Infrared;
uint8_t Body;
uint8_t BodyIndex;
uint8_t LongExposureInfrared;

virtual std::string RRType() {return "edu.rpi.cats.sensors.kinect2.KinectMultiSource";  }
};

class Kinect : public virtual edu::rpi::cats::sensors::camera_interface::Camera
{
public:
virtual void StartStreaming()=0;

virtual void StopStreaming()=0;

virtual uint8_t EnableSensors(RR_SHARED_PTR<KinectMultiSource > s)=0;

virtual uint8_t DisableSensors()=0;

virtual RR_SHARED_PTR<KinectMultiSource > SensorsEnabled()=0;

virtual RR_SHARED_PTR<edu::rpi::cats::sensors::camera_interface::ImageHeader > getImageHeader()=0;

virtual RR_SHARED_PTR<edu::rpi::cats::sensors::camera_interface::ImageHeader > getDepthImageHeader()=0;

virtual RR_SHARED_PTR<edu::rpi::cats::sensors::camera_interface::Image > getCurrentImage()=0;

virtual RR_SHARED_PTR<edu::rpi::cats::sensors::camera_interface::Image16 > getCurrentDepthImage()=0;

virtual RR_SHARED_PTR<edu::rpi::cats::sensors::camera_interface::Image16 > getCurrentInfraredImage()=0;

virtual RR_SHARED_PTR<edu::rpi::cats::sensors::camera_interface::Image > getCurrentBodyIndexImage()=0;

virtual RR_SHARED_PTR<edu::rpi::cats::sensors::camera_interface::Image16 > getCurrentLongExposureInfraredImage()=0;

virtual RR_SHARED_PTR<RobotRaconteur::RRArray<uint64_t > > getTrackedBodyIDs()=0;

virtual RR_SHARED_PTR<KinectBody > getDetectedBody(int32_t index)=0;

virtual RR_SHARED_PTR<RobotRaconteur::Pipe<RR_SHARED_PTR<edu::rpi::cats::sensors::camera_interface::Image > > > get_ImageStream()=0;
virtual void set_ImageStream(RR_SHARED_PTR<RobotRaconteur::Pipe<RR_SHARED_PTR<edu::rpi::cats::sensors::camera_interface::Image > > > value)=0;

virtual std::string RRType() {return "edu.rpi.cats.sensors.kinect2.Kinect";  }
};

}
}
}
}
}

